name: Check Master PRs

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  blockPR:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Check target branch
        if: github.ref == 'refs/heads/master'
        run: |
          echo "PRs to the master branch are not allowed."
          echo "::error ::PRs to the master branch are not allowed."
          exit 1

      - name: Notify User
        if: always() && github.ref == 'refs/heads/master'
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue_number = context.issue.number;
            const message = "⚠️ **ОШЫБКА**: Ты создал PR в master ветку. PR-ы можно создавать только в СВОЮ ветку. Пожалуйста, нажми кнопку Edit вверху и измени ветку, в которую направляешь PR.";
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: message
            });