name: Block PRs to Master Branch

on:
  pull_request_target:
    branches:
      - master

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  blockPR:
    runs-on: ubuntu-latest
    steps:
      - name: Block Master PR
        run: |
          echo "PRs to the master branch are not allowed."
          exit 1  # Explicitly failing the job

      - name: Post Comment
        if: always()  # Ensures this runs regardless of the previous step's result
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const pr = ${GITHUB_EVENT_PATH};
            const issue_number = pr.pull_request.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const message = "⚠️ PRs to the master branch are not allowed. Please target your PR to a different branch.";
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number,
              body: message
            });